# Generated by Django 2.1.7 on 2019-03-05 21:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 5, 21, 44, 54, 191303), verbose_name='date published'),
        ),
    ]
