# Generated by Django 2.1.7 on 2019-03-05 23:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190305_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 5, 23, 15, 37, 761583), verbose_name='date published'),
        ),
    ]
