# Generated by Django 2.1.7 on 2019-03-06 15:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20190306_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 6, 15, 51, 41, 397067), verbose_name='date published'),
        ),
    ]
